# Generated by Django 3.2.10 on 2023-07-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_app_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
